// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/booking-wizard/CompactProgressWizard.tsx": () => import("../components/mockups/booking-wizard/CompactProgressWizard.tsx"),
  "./components/mockups/booking-wizard/QueueFast.tsx": () => import("../components/mockups/booking-wizard/QueueFast.tsx"),
  "./components/mockups/booking-wizard/Wizard.tsx": () => import("../components/mockups/booking-wizard/Wizard.tsx"),
  "./components/mockups/booking-wizard/WizardVariant.tsx": () => import("../components/mockups/booking-wizard/WizardVariant.tsx")
};
